
spring:
 application:
   name: pollowgangsan

 mvc:
   view:
     prefix: /views/
     suffix: .jsp
     
#db-mysql
 datasource:
    url: jdbc:mysql://localhost:3306/jsptest
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: totoro
    password: totoro123

mybatis:
   type-aliases-package: jjon.gangsan.model
   mapper-locations: classpath:/mapper/*.xml
   config-location: classpath:Mybatis-Config.xml



server:
 port: 80





