#  application:
#    name: weatherTest

mybatis:
    type-aliases-package: jjon.gangsan.model
    mapper-locations: classpath:/mapper/*.xml
    config-location: classpath:Mybatis-Config.xml

spring:
  application:
    name: weatherTest
   
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/weather?serverTimezone=Asia/Seoul
      username: weather
      password: 1234
 
 


   
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
      





