

spring:
 application:
   name: pollowgangsan

 mvc:
   view:
     prefix: /views/
     suffix: .jsp

 session:
   store-type: jdbc # 세션 저장소로 JDBC를 사용합니다.
   jdbc:
     initialize-schema: always # 스키마를 초기화합니다.     
#db-mysql
 datasource:
      url: jdbc:mysql://localhost:3306/testProject
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: test
      password: 1234

mybatis:
   type-aliases-package: jjon.gangsan.model
   mapper-locations: classpath:/mapper/*.xml
   config-location: classpath:Mybatis-Config.xml

#port
server:
  port: 80
 







